project_id = "noshwvwpjtnvndokbfjx"

[functions.google-calendar-list-calendars]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.delete-user-complete]
verify_jwt = false

[functions.system-finance-categories]
verify_jwt = false

[functions.system-finance-transactions]
verify_jwt = false

[functions.system-finance-summary]
verify_jwt = false

[functions.system-finance-import-revenue]
verify_jwt = false
