import { useState } from "react";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Clock,
  FileText,
  MessageSquare,
  AlertCircle,
  RefreshCw,
  Calendar,
  TrendingUp,
  CheckCircle2,
  XCircle,
  Loader2,
  Copy,
  ExternalLink,
  MessageCircle,
} from "lucide-react";
import { copyMessageToClipboard, openWhatsAppWeb } from "@/lib/whatsappUtils";
import { getPublicInvoiceUrl } from "@/lib/publicUrl";
import {
  useRecurringInvoiceLogs,
  useRecurringInvoiceStats,
  useAutoGeneratedInvoices,
  useUpcomingRecurrences,
  RecurringInvoiceLog,
} from "@/hooks/useRecurringInvoiceLogs";

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(value);
}

function formatDate(date: string): string {
  return format(new Date(date), "dd/MM/yyyy 'às' HH:mm", { locale: ptBR });
}

function formatShortDate(date: string): string {
  return format(new Date(date), "dd/MM/yyyy", { locale: ptBR });
}

// Função para gerar mensagem de fatura
function generateInvoiceMessage(invoice: any): string {
  const clientName = invoice.client?.name || 'Cliente';
  const serviceName = invoice.service?.name || invoice.description || 'Serviço';
  const amount = formatCurrency(invoice.amount);
  const dueDate = formatShortDate(invoice.due_date);
  const invoiceNumber = invoice.invoice_number || invoice.id.slice(0, 8).toUpperCase();
  const invoiceLink = getPublicInvoiceUrl(invoice.id);

  return `📄 *Fatura - Mostralo*

Olá ${clientName}!

Segue sua fatura para pagamento:

📋 *Fatura:* #${invoiceNumber}
📝 *Serviço:* ${serviceName}
💰 *Valor:* ${amount}
📅 *Vencimento:* ${dueDate}

💳 *Pagar agora:*
${invoiceLink}

Qualquer dúvida, estamos à disposição!`;
}

export function RecurringInvoicesReport() {
  const [activeTab, setActiveTab] = useState("overview");
  
  const { data: logs, isLoading: logsLoading, refetch: refetchLogs } = useRecurringInvoiceLogs(50);
  const { data: stats, isLoading: statsLoading, refetch: refetchStats } = useRecurringInvoiceStats();
  const { data: autoGenerated, isLoading: autoLoading, refetch: refetchAuto } = useAutoGeneratedInvoices(50);
  const { data: upcoming, isLoading: upcomingLoading, refetch: refetchUpcoming } = useUpcomingRecurrences(20);

  const handleRefresh = () => {
    refetchLogs();
    refetchStats();
    refetchAuto();
    refetchUpcoming();
  };

  const isLoading = logsLoading || statsLoading || autoLoading || upcomingLoading;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-lg font-semibold">Relatório de Recorrências</h2>
          <p className="text-sm text-muted-foreground">
            Histórico de execuções do CRON e faturas geradas automaticamente
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={handleRefresh} disabled={isLoading}>
          <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? "animate-spin" : ""}`} />
          Atualizar
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Clock className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalLogs || 0}</p>
                <p className="text-xs text-muted-foreground">Execuções</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-green-500/10 rounded-lg">
                <FileText className="h-5 w-5 text-green-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalInvoicesCreated || 0}</p>
                <p className="text-xs text-muted-foreground">Faturas Criadas</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-500/10 rounded-lg">
                <MessageSquare className="h-5 w-5 text-blue-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalWhatsappSent || 0}</p>
                <p className="text-xs text-muted-foreground">WhatsApp Enviados</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-red-500/10 rounded-lg">
                <AlertCircle className="h-5 w-5 text-red-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalErrors || 0}</p>
                <p className="text-xs text-muted-foreground">Erros</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Last execution info */}
      {stats?.lastExecution && (
        <div className="text-sm text-muted-foreground flex items-center gap-2">
          <Calendar className="h-4 w-4" />
          Última execução: {formatDate(stats.lastExecution)}
        </div>
      )}

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="overview" className="text-xs sm:text-sm">
            Histórico CRON
          </TabsTrigger>
          <TabsTrigger value="generated" className="text-xs sm:text-sm">
            Faturas Geradas
          </TabsTrigger>
          <TabsTrigger value="upcoming" className="text-xs sm:text-sm">
            Próximas
          </TabsTrigger>
        </TabsList>

        {/* CRON History */}
        <TabsContent value="overview" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Histórico de Execuções</CardTitle>
              <CardDescription>
                Registro de todas as execuções automáticas e manuais
              </CardDescription>
            </CardHeader>
            <CardContent>
              {logsLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : !logs || logs.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  <Clock className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Nenhuma execução registrada ainda</p>
                  <p className="text-sm">O CRON executa diariamente às 08:00 UTC</p>
                </div>
              ) : (
                <Accordion type="single" collapsible className="w-full">
                  {logs.map((log: RecurringInvoiceLog) => (
                    <AccordionItem key={log.id} value={log.id}>
                      <AccordionTrigger className="hover:no-underline">
                        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-left w-full pr-4">
                          <span className="text-sm font-medium">
                            {formatDate(log.executed_at)}
                          </span>
                          <div className="flex flex-wrap gap-2">
                            <Badge variant={log.execution_source === "cron" ? "secondary" : "outline"}>
                              {log.execution_source === "cron" ? "Automático" : "Manual"}
                            </Badge>
                            {log.invoices_created > 0 && (
                              <Badge variant="default" className="bg-green-500">
                                {log.invoices_created} fatura(s)
                              </Badge>
                            )}
                            {log.whatsapp_sent > 0 && (
                              <Badge variant="default" className="bg-blue-500">
                                {log.whatsapp_sent} WhatsApp
                              </Badge>
                            )}
                            {log.errors_count > 0 && (
                              <Badge variant="destructive">
                                {log.errors_count} erro(s)
                              </Badge>
                            )}
                            {log.invoices_created === 0 && log.errors_count === 0 && (
                              <Badge variant="outline">Nenhuma pendente</Badge>
                            )}
                          </div>
                        </div>
                      </AccordionTrigger>
                      <AccordionContent>
                        <div className="space-y-4 pt-2">
                          {/* Summary */}
                          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
                            <div>
                              <span className="text-muted-foreground">Processadas:</span>
                              <span className="ml-2 font-medium">{log.total_processed}</span>
                            </div>
                            <div>
                              <span className="text-muted-foreground">Criadas:</span>
                              <span className="ml-2 font-medium">{log.invoices_created}</span>
                            </div>
                            <div>
                              <span className="text-muted-foreground">WhatsApp:</span>
                              <span className="ml-2 font-medium">{log.whatsapp_sent}</span>
                            </div>
                            <div>
                              <span className="text-muted-foreground">Erros:</span>
                              <span className="ml-2 font-medium">{log.errors_count}</span>
                            </div>
                          </div>

                          {/* Invoices created */}
                          {log.execution_details?.invoices && log.execution_details.invoices.length > 0 && (
                            <div>
                              <h4 className="text-sm font-medium mb-2">Faturas Criadas:</h4>
                              <div className="space-y-2">
                                {log.execution_details.invoices.map((inv) => (
                                  <div
                                    key={inv.id}
                                    className="flex flex-col sm:flex-row sm:items-center gap-2 p-2 bg-muted/50 rounded-lg text-sm"
                                  >
                                    <span className="font-mono">{inv.invoice_number}</span>
                                    <span className="text-muted-foreground">•</span>
                                    <span>{inv.client_name}</span>
                                    <span className="text-muted-foreground">•</span>
                                    <span className="font-medium">{formatCurrency(inv.amount)}</span>
                                    <span className="text-muted-foreground">•</span>
                                    <span>Venc: {formatShortDate(inv.due_date)}</span>
                                    {inv.whatsapp_sent && (
                                      <Badge variant="outline" className="ml-auto">
                                        <MessageSquare className="h-3 w-3 mr-1" />
                                        Enviado
                                      </Badge>
                                    )}
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}

                          {/* Errors */}
                          {log.execution_details?.errors && log.execution_details.errors.length > 0 && (
                            <div>
                              <h4 className="text-sm font-medium text-red-500 mb-2">Erros:</h4>
                              <div className="space-y-1">
                                {log.execution_details.errors.map((err, i) => (
                                  <div
                                    key={i}
                                    className="text-sm p-2 bg-red-50 dark:bg-red-950/20 rounded text-red-600 dark:text-red-400"
                                  >
                                    {err}
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Auto Generated Invoices */}
        <TabsContent value="generated" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Faturas Geradas Automaticamente</CardTitle>
              <CardDescription>
                Lista de todas as faturas criadas pelo processamento recorrente
              </CardDescription>
            </CardHeader>
            <CardContent>
              {autoLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : !autoGenerated || autoGenerated.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  <TrendingUp className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Nenhuma fatura gerada automaticamente</p>
                  <p className="text-sm">Faturas serão listadas aqui quando forem criadas pelo CRON</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Nº Fatura</TableHead>
                        <TableHead>Cliente</TableHead>
                        <TableHead>Valor</TableHead>
                        <TableHead>Vencimento</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead className="text-right">Ações</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {autoGenerated.map((invoice: any) => (
                        <TableRow key={invoice.id}>
                          <TableCell className="font-mono text-sm">
                            {invoice.invoice_number}
                          </TableCell>
                          <TableCell>{invoice.client?.name || "N/A"}</TableCell>
                          <TableCell>{formatCurrency(invoice.amount)}</TableCell>
                          <TableCell>{formatShortDate(invoice.due_date)}</TableCell>
                          <TableCell>
                            <Badge
                              variant={
                                invoice.payment_status === "paid"
                                  ? "default"
                                  : invoice.payment_status === "pending"
                                  ? "secondary"
                                  : "destructive"
                              }
                            >
                              {invoice.payment_status === "paid" && (
                                <CheckCircle2 className="h-3 w-3 mr-1" />
                              )}
                              {invoice.payment_status === "cancelled" && (
                                <XCircle className="h-3 w-3 mr-1" />
                              )}
                              {invoice.payment_status === "paid"
                                ? "Pago"
                                : invoice.payment_status === "pending"
                                ? "Pendente"
                                : invoice.payment_status === "overdue"
                                ? "Vencido"
                                : "Cancelado"}
                            </Badge>
                          </TableCell>
                          <TableCell className="text-right">
                            <div className="flex items-center justify-end gap-1">
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={() => {
                                  const message = generateInvoiceMessage(invoice);
                                  copyMessageToClipboard(message);
                                }}
                                title="Copiar mensagem"
                              >
                                <Copy className="h-4 w-4" />
                              </Button>
                              {invoice.client?.phone && (
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 text-green-600 hover:text-green-700"
                                  onClick={() => {
                                    const message = generateInvoiceMessage(invoice);
                                    openWhatsAppWeb(invoice.client.phone, message);
                                  }}
                                  title="Abrir WhatsApp Web"
                                >
                                  <MessageCircle className="h-4 w-4" />
                                </Button>
                              )}
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={() => window.open(getPublicInvoiceUrl(invoice.id), '_blank')}
                                title="Ver fatura"
                              >
                                <ExternalLink className="h-4 w-4" />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Upcoming Recurrences */}
        <TabsContent value="upcoming" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Próximas Recorrências</CardTitle>
              <CardDescription>
                Faturas recorrentes que serão processadas nos próximos ciclos
              </CardDescription>
            </CardHeader>
            <CardContent>
              {upcomingLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : !upcoming || upcoming.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  <Calendar className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Nenhuma recorrência próxima</p>
                  <p className="text-sm">Faturas recorrentes pagas aparecerão aqui</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Cliente</TableHead>
                        <TableHead>Serviço</TableHead>
                        <TableHead>Valor</TableHead>
                        <TableHead>Tipo</TableHead>
                        <TableHead>Próx. Vencimento</TableHead>
                        <TableHead>Ciclo</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {upcoming.map((invoice: any) => (
                        <TableRow key={invoice.id}>
                          <TableCell>{invoice.client?.name || "N/A"}</TableCell>
                          <TableCell className="text-muted-foreground">
                            {invoice.service?.name || invoice.description || "N/A"}
                          </TableCell>
                          <TableCell>{formatCurrency(invoice.amount)}</TableCell>
                          <TableCell>
                            <Badge variant="outline">
                              {invoice.recurrence_type === "monthly"
                                ? "Mensal"
                                : invoice.recurrence_type === "quarterly"
                                ? "Trimestral"
                                : "Anual"}
                            </Badge>
                          </TableCell>
                          <TableCell className="font-medium">
                            {formatShortDate(invoice.next_due_date)}
                          </TableCell>
                          <TableCell className="text-sm text-muted-foreground">
                            {invoice.recurrence_count
                              ? `${invoice.recurrence_current || 0}/${invoice.recurrence_count}`
                              : "∞"}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
