import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export interface RecurringInvoiceLog {
  id: string;
  executed_at: string;
  total_processed: number;
  invoices_created: number;
  whatsapp_sent: number;
  errors_count: number;
  execution_details: {
    invoices?: Array<{
      id: string;
      invoice_number: string;
      client_name: string;
      amount: number;
      due_date: string;
      whatsapp_sent: boolean;
    }>;
    errors?: string[];
  } | null;
  execution_source: string;
  created_at: string;
}

export interface RecurringInvoiceStats {
  totalLogs: number;
  totalInvoicesCreated: number;
  totalWhatsappSent: number;
  totalErrors: number;
  lastExecution: string | null;
}

export function useRecurringInvoiceLogs(limit: number = 50) {
  return useQuery({
    queryKey: ["recurring-invoice-logs", limit],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("recurring_invoice_logs")
        .select("*")
        .order("executed_at", { ascending: false })
        .limit(limit);

      if (error) throw error;
      return data as RecurringInvoiceLog[];
    },
  });
}

export function useRecurringInvoiceStats() {
  return useQuery({
    queryKey: ["recurring-invoice-stats"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("recurring_invoice_logs")
        .select("*")
        .order("executed_at", { ascending: false });

      if (error) throw error;

      const logs = data as RecurringInvoiceLog[];

      // Recorte dos últimos 30 dias para os contadores do topo
      const now = Date.now();
      const thirtyDaysAgo = now - 30 * 24 * 60 * 60 * 1000;
      const logsLast30 = logs.filter(
        (log) => new Date(log.executed_at).getTime() >= thirtyDaysAgo
      );

      const stats: RecurringInvoiceStats = {
        totalLogs: logs.length,
        totalInvoicesCreated: logs.reduce((acc, log) => acc + log.invoices_created, 0),
        totalWhatsappSent: logs.reduce((acc, log) => acc + log.whatsapp_sent, 0),
        totalErrors: logs.reduce((acc, log) => acc + log.errors_count, 0),
        lastExecution: logs.length > 0 ? logs[0].executed_at : null,
        last30Days: {
          totalLogs: logsLast30.length,
          totalInvoicesCreated: logsLast30.reduce((acc, log) => acc + log.invoices_created, 0),
          totalWhatsappSent: logsLast30.reduce((acc, log) => acc + log.whatsapp_sent, 0),
          totalErrors: logsLast30.reduce((acc, log) => acc + log.errors_count, 0),
        },
      };

      return stats;
    },
  });
}

export function useAutoGeneratedInvoices(limit: number = 50) {
  return useQuery({
    queryKey: ["auto-generated-invoices", limit],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("external_invoices")
        .select(`
          *,
          client:external_clients(*),
          service:external_services(*),
          parent:external_invoices!parent_invoice_id(invoice_number)
        `)
        .not("parent_invoice_id", "is", null)
        .order("created_at", { ascending: false })
        .limit(limit);

      if (error) throw error;
      return data;
    },
  });
}

export function useUpcomingRecurrences(limit: number = 20) {
  return useQuery({
    queryKey: ["upcoming-recurrences", limit],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("external_invoices")
        .select(`
          *,
          client:external_clients(*),
          service:external_services(*)
        `)
        .eq("is_recurring", true)
        .eq("payment_status", "paid")
        .not("next_due_date", "is", null)
        .order("next_due_date", { ascending: true })
        .limit(limit);

      if (error) throw error;
      return data;
    },
  });
}
