import { Database } from "@/integrations/supabase/types";

type Order = Database['public']['Tables']['orders']['Row'];
type OrderItem = Database['public']['Tables']['order_items']['Row'];

export const generateMockOrderNumber = (index: number) => {
  return `#${String(index + 1).padStart(4, '0')}`;
};

export const mockOrders: Partial<Order>[] = [
  {
    id: 'mock-order-1',
    order_number: '#0001',
    store_id: '00000000-0000-0000-0000-000000000000', // Store ID mockup
    customer_name: 'João Silva',
    customer_phone: '(11) 98765-4321',
    customer_email: 'joao@email.com',
    customer_address: 'Rua das Flores, 123 - Centro',
    delivery_type: 'delivery',
    payment_method: 'pix',
    payment_status: 'pending',
    status: 'entrada',
    subtotal: 45.50,
    delivery_fee: 8.00,
    total: 53.50,
    notes: 'Sem cebola no hambúrguer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-order-2',
    order_number: '#0002',
    store_id: '00000000-0000-0000-0000-000000000000',
    customer_name: 'Maria Santos',
    customer_phone: '(11) 97654-3210',
    customer_email: 'maria@email.com',
    customer_address: 'Av. Principal, 456 - Jardins',
    delivery_type: 'delivery',
    payment_method: 'card',
    payment_status: 'paid',
    status: 'em_preparo',
    subtotal: 78.90,
    delivery_fee: 10.00,
    total: 88.90,
    notes: 'Caprichar no molho',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(), // 15 min atrás
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'mock-order-3',
    order_number: '#0003',
    store_id: '00000000-0000-0000-0000-000000000000',
    customer_name: 'Pedro Oliveira',
    customer_phone: '(11) 96543-2109',
    delivery_type: 'pickup',
    payment_method: 'cash',
    payment_status: 'pending',
    status: 'aguarda_retirada',
    subtotal: 32.00,
    delivery_fee: 0,
    total: 32.00,
    notes: null,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(), // 30 min atrás
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'mock-order-4',
    order_number: '#0004',
    store_id: '00000000-0000-0000-0000-000000000000',
    customer_name: 'Ana Costa',
    customer_phone: '(11) 95432-1098',
    customer_email: 'ana@email.com',
    customer_address: 'Rua do Comércio, 789 - Vila Nova',
    delivery_type: 'delivery',
    payment_method: 'pix',
    payment_status: 'paid',
    status: 'em_transito',
    subtotal: 125.00,
    delivery_fee: 12.00,
    total: 137.00,
    notes: 'Deixar com o porteiro',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(), // 45 min atrás
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'mock-order-5',
    order_number: '#0005',
    store_id: '00000000-0000-0000-0000-000000000000',
    customer_name: 'Carlos Mendes',
    customer_phone: '(11) 94321-0987',
    delivery_type: 'pickup',
    payment_method: 'card',
    payment_status: 'paid',
    status: 'entrada',
    subtotal: 56.50,
    delivery_fee: 0,
    total: 56.50,
    notes: 'Adicionar guardanapos extras',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(), // 5 min atrás
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'mock-order-6',
    order_number: '#0006',
    store_id: '00000000-0000-0000-0000-000000000000',
    customer_name: 'Beatriz Lima',
    customer_phone: '(11) 93210-9876',
    customer_email: 'beatriz@email.com',
    customer_address: 'Av. Paulista, 1000 - Bela Vista',
    delivery_type: 'delivery',
    payment_method: 'pix',
    payment_status: 'paid',
    status: 'em_preparo',
    subtotal: 92.00,
    delivery_fee: 15.00,
    total: 107.00,
    notes: 'Andar 15, apto 152',
    created_at: new Date(Date.now() - 20 * 60000).toISOString(), // 20 min atrás
    updated_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
];

export const mockOrderItems: Record<string, Partial<OrderItem>[]> = {
  'mock-order-1': [
    {
      id: 'mock-item-1-1',
      order_id: 'mock-order-1',
      product_name: 'Hambúrguer Especial',
      quantity: 2,
      unit_price: 18.50,
      subtotal: 37.00,
      notes: 'Sem cebola',
    },
    {
      id: 'mock-item-1-2',
      order_id: 'mock-order-1',
      product_name: 'Batata Frita',
      quantity: 1,
      unit_price: 8.50,
      subtotal: 8.50,
      notes: null,
    },
  ],
  'mock-order-2': [
    {
      id: 'mock-item-2-1',
      order_id: 'mock-order-2',
      product_name: 'Pizza Margherita',
      quantity: 1,
      unit_price: 49.90,
      subtotal: 49.90,
      notes: 'Massa fina',
    },
    {
      id: 'mock-item-2-2',
      order_id: 'mock-order-2',
      product_name: 'Refrigerante 2L',
      quantity: 2,
      unit_price: 14.50,
      subtotal: 29.00,
      notes: null,
    },
  ],
  'mock-order-3': [
    {
      id: 'mock-item-3-1',
      order_id: 'mock-order-3',
      product_name: 'Sanduíche Natural',
      quantity: 2,
      unit_price: 16.00,
      subtotal: 32.00,
      notes: null,
    },
  ],
  'mock-order-4': [
    {
      id: 'mock-item-4-1',
      order_id: 'mock-order-4',
      product_name: 'Sushi Combo 30 peças',
      quantity: 1,
      unit_price: 95.00,
      subtotal: 95.00,
      notes: 'Sem wasabi',
    },
    {
      id: 'mock-item-4-2',
      order_id: 'mock-order-4',
      product_name: 'Temaki Salmão',
      quantity: 2,
      unit_price: 15.00,
      subtotal: 30.00,
      notes: null,
    },
  ],
  'mock-order-5': [
    {
      id: 'mock-item-5-1',
      order_id: 'mock-order-5',
      product_name: 'Açaí 500ml',
      quantity: 2,
      unit_price: 22.00,
      subtotal: 44.00,
      notes: 'Com granola e banana',
    },
    {
      id: 'mock-item-5-2',
      order_id: 'mock-order-5',
      product_name: 'Suco Natural',
      quantity: 1,
      unit_price: 12.50,
      subtotal: 12.50,
      notes: null,
    },
  ],
  'mock-order-6': [
    {
      id: 'mock-item-6-1',
      order_id: 'mock-order-6',
      product_name: 'Prato Executivo',
      quantity: 2,
      unit_price: 35.00,
      subtotal: 70.00,
      notes: 'Arroz e feijão separados',
    },
    {
      id: 'mock-item-6-2',
      order_id: 'mock-order-6',
      product_name: 'Sobremesa',
      quantity: 2,
      unit_price: 11.00,
      subtotal: 22.00,
      notes: null,
    },
  ],
};
