-- Inserir 10 templates padrão de enquete e lista
INSERT INTO public.whatsapp_templates (name, category, message_type, content, is_active, is_default, store_id, poll_question, poll_options, poll_selectable_count, list_title, list_button_text, list_sections)
VALUES 
-- 5 TEMPLATES DE ENQUETE
('📊 Enquete Satisfação', 'agradecimento', 'poll', E'Olá {primeiro_nome}! 👋\n\nSeu pedido foi entregue com sucesso! Gostaríamos de saber sua opinião:', true, true, NULL, 'Como foi sua experiência com a {loja}?', '["⭐ Excelente", "😊 Boa", "😐 Regular", "😔 Ruim"]', 1, NULL, NULL, NULL),

('🎁 Enquete Preferência Promoção', 'promocao', 'poll', E'Oi {primeiro_nome}! 🎉\n\nQueremos criar promoções especiais pra você! Nos conta:', true, true, NULL, 'Qual tipo de promoção você prefere?', '["🍕 2 por 1", "💰 Desconto 20%", "🚚 Frete Grátis", "🎁 Ganhe um Brinde"]', 1, NULL, NULL, NULL),

('⏰ Enquete Horário Preferido', 'boas_vindas', 'poll', E'Bem-vindo à {loja}! 🎊\n\nPara te conhecer melhor, conta pra gente:', true, true, NULL, 'Qual horário você costuma pedir?', '["☀️ Almoço (11h-14h)", "🌅 Tarde (14h-18h)", "🌙 Jantar (18h-21h)", "🌃 Noite (após 21h)"]', 1, NULL, NULL, NULL),

('💔 Enquete Recompra', 'recuperacao', 'poll', E'Oi {primeiro_nome}! 😢\n\nSentimos sua falta! Faz {dias_inativo} dias desde seu último pedido.', true, true, NULL, 'O que te faria pedir novamente?', '["💰 Cupom de Desconto", "🚚 Frete Grátis", "🆕 Novos Produtos", "⏱️ Entrega Mais Rápida"]', 1, NULL, NULL, NULL),

('📝 Enquete Feedback', 'agradecimento', 'poll', E'Olá {primeiro_nome}! 🙏\n\nObrigado por ser nosso cliente! Sua opinião é muito importante:', true, true, NULL, 'O que podemos melhorar?', '["🚀 Tempo de Entrega", "📦 Embalagem", "😋 Variedade", "💬 Atendimento"]', 1, NULL, NULL, NULL),

-- 5 TEMPLATES DE LISTA
('📋 Lista Cardápio', 'promocao', 'list', E'Olá {primeiro_nome}! 😋\n\nConfira nosso cardápio completo e escolha seu favorito!\n\n🏷️ Acesse: {link_loja}', true, true, NULL, NULL, NULL, NULL, 'Cardápio {loja}', '📋 Ver Cardápio', '[{"title":"🍕 Pizzas","rows":[{"title":"Margherita","description":"Molho, mussarela e manjericão"},{"title":"Calabresa","description":"Calabresa fatiada e cebola"},{"title":"4 Queijos","description":"Mussarela, provolone, parmesão e gorgonzola"}]},{"title":"🍔 Lanches","rows":[{"title":"Hambúrguer Clássico","description":"Carne 180g, queijo e salada"},{"title":"X-Bacon","description":"Carne, bacon crocante e cheddar"}]},{"title":"🥤 Bebidas","rows":[{"title":"Refrigerantes","description":"Coca, Guaraná, Sprite 350ml"},{"title":"Sucos Naturais","description":"Laranja, Limão, Maracujá"}]}]'),

('🎁 Lista Combos', 'promocao', 'list', E'Oi {primeiro_nome}! 🤩\n\nTemos combos especiais com preços imperdíveis!\n\nEscolha o seu favorito:', true, true, NULL, NULL, NULL, NULL, 'Combos Especiais', '🎁 Ver Combos', '[{"title":"🍕 Combos Individual","rows":[{"title":"Combo Solo","description":"1 Pizza M + Refri - R$ 39,90"},{"title":"Combo Lanche","description":"1 Hambúrguer + Batata + Refri - R$ 32,90"},{"title":"Combo Fitness","description":"1 Salada + Suco Natural - R$ 28,90"}]},{"title":"👨‍👩‍👧‍👦 Combos Família","rows":[{"title":"Combo Família G","description":"1 Pizza G + 2 Refris - R$ 69,90"},{"title":"Super Família","description":"2 Pizzas G + 4 Refris - R$ 119,90"},{"title":"Festa em Casa","description":"3 Pizzas G + 6 Refris + Sobremesa - R$ 159,90"}]}]'),

('🔥 Lista Promoções', 'promocao', 'list', E'Eii {primeiro_nome}! 🔥\n\nOfertas imperdíveis só hoje!\n\nConfira e garanta já:', true, true, NULL, NULL, NULL, NULL, 'Promoções Especiais', '🔥 Ver Ofertas', '[{"title":"⚡ Ofertas do Dia","rows":[{"title":"Pizza Margherita","description":"De R$ 45,90 por R$ 29,90"},{"title":"Combo Terça","description":"2 Hambúrgueres por R$ 39,90"},{"title":"Frete Grátis","description":"Pedidos acima de R$ 50"}]},{"title":"📅 Ofertas da Semana","rows":[{"title":"Segunda Fit","description":"Saladas com 30% OFF"},{"title":"Quarta da Pizza","description":"Todas pizzas com 20% OFF"},{"title":"Domingo em Família","description":"Combos família com 25% OFF"}]}]'),

('📖 Lista Explorar', 'boas_vindas', 'list', E'Olá {primeiro_nome}! 🎉\n\nBem-vindo(a) à {loja}!\n\nConheça nosso cardápio e descubra delícias:', true, true, NULL, NULL, NULL, NULL, 'Explore nosso cardápio', '📖 Explorar Cardápio', '[{"title":"🏆 Mais Pedidos","rows":[{"title":"Pizza Calabresa","description":"⭐ 4.9 - Favorito dos clientes"},{"title":"X-Tudo","description":"⭐ 4.8 - Completo e saboroso"},{"title":"Açaí 500ml","description":"⭐ 4.9 - Refrescante e nutritivo"}]},{"title":"🆕 Novidades","rows":[{"title":"Pizza de Costela","description":"Lançamento exclusivo!"},{"title":"Burguer Angus","description":"Carne premium 200g"}]},{"title":"💎 Especiais do Chef","rows":[{"title":"Risoto de Camarão","description":"Preparação especial"},{"title":"Filé ao Molho Madeira","description":"Acompanha arroz e batata"}]}]'),

('🏆 Lista Fidelidade', 'agradecimento', 'list', E'Oi {primeiro_nome}! 🌟\n\nVocê já tem {total_pedidos} pedidos conosco!\n\nVeja suas vantagens exclusivas:', true, true, NULL, NULL, NULL, NULL, 'Suas Vantagens VIP', '🏆 Ver Vantagens', '[{"title":"🎟️ Cupons Disponíveis","rows":[{"title":"FRETE10","description":"R$ 10 OFF na taxa de entrega"},{"title":"VOLTE15","description":"15% OFF no próximo pedido"},{"title":"PIZZA2X1","description":"Compre 1 pizza, leve 2"}]},{"title":"🎯 Próximos Benefícios","rows":[{"title":"VIP Bronze (5 pedidos)","description":"Frete grátis permanente"},{"title":"VIP Prata (15 pedidos)","description":"10% OFF em tudo"},{"title":"VIP Ouro (30 pedidos)","description":"Brinde a cada pedido"}]}]');