-- Inserir 100+ versículos bíblicos organizados por categoria
INSERT INTO public.bible_verses (verse_text, reference, book, category) VALUES
-- DILIGÊNCIA E TRABALHO (25)
('A alma dos diligentes se fartará.', 'Provérbios 13:4', 'Provérbios', 'diligencia'),
('A mão dos diligentes dominará, mas os negligentes serão tributários.', 'Provérbios 12:24', 'Provérbios', 'diligencia'),
('Viste um homem diligente na sua obra? Perante reis será posto; não permanecerá entre os de posição inferior.', 'Provérbios 22:29', 'Provérbios', 'diligencia'),
('O que lavra a sua terra virá a fartar-se de pão, mas o que segue os ociosos se fartará de pobreza.', 'Provérbios 28:19', 'Provérbios', 'diligencia'),
('Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos e sê sábio.', 'Provérbios 6:6', 'Provérbios', 'diligencia'),
('O trabalhador tem direito ao seu sustento.', 'Provérbios 10:4', 'Provérbios', 'diligencia'),
('Anda na presença dos sábios e serás sábio; mas o companheiro dos tolos sofrerá.', 'Provérbios 13:20', 'Provérbios', 'diligencia'),
('O pensamento do diligente tende só à abundância, mas o de todo apressado, à pobreza.', 'Provérbios 21:5', 'Provérbios', 'diligencia'),
('O homem diligente alcançará riquezas.', 'Provérbios 10:4', 'Provérbios', 'diligencia'),
('Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados, porque o Senhor, o seu Deus, vai com vocês.', 'Deuteronômio 31:6', 'Deuteronômio', 'diligencia'),
('Tudo quanto te vier à mão para fazer, faze-o conforme as tuas forças.', 'Eclesiastes 9:10', 'Eclesiastes', 'diligencia'),
('O preguiçoso deseja, e nada alcança, mas a alma dos diligentes se fartará.', 'Provérbios 13:4', 'Provérbios', 'diligencia'),
('Melhor é o fim das coisas do que o princípio delas; melhor é o paciente de espírito do que o soberbo de espírito.', 'Eclesiastes 7:8', 'Eclesiastes', 'diligencia'),
('Semeai para vós em justiça, colhei segundo a misericórdia.', 'Oseias 10:12', 'Oseias', 'diligencia'),
('O que semeia a iniquidade segará males.', 'Provérbios 22:8', 'Provérbios', 'diligencia'),
('Na lavoura há abundância de trigo, mas há quem seja destruído por não ter juízo.', 'Provérbios 13:23', 'Provérbios', 'diligencia'),
('O trabalhador cuidadoso terá fartura.', 'Provérbios 12:11', 'Provérbios', 'diligencia'),
('Quem cuida da figueira comerá do seu fruto.', 'Provérbios 27:18', 'Provérbios', 'diligencia'),
('Não trabalheis pela comida que perece, mas pela que permanece para a vida eterna.', 'João 6:27', 'João', 'diligencia'),
('Tudo o que fizerem, façam de todo o coração, como para o Senhor.', 'Colossenses 3:23', 'Colossenses', 'diligencia'),
('Aquele que não trabalha, também não coma.', '2 Tessalonicenses 3:10', '2 Tessalonicenses', 'diligencia'),
('Trabalhem de boa vontade, como se estivessem servindo ao Senhor.', 'Efésios 6:7', 'Efésios', 'diligencia'),
('Os planos do diligente conduzem à abundância.', 'Provérbios 21:5', 'Provérbios', 'diligencia'),
('O que ajunta no verão é filho prudente, mas o que dorme na sega é filho que causa vergonha.', 'Provérbios 10:5', 'Provérbios', 'diligencia'),
('Em todo trabalho há proveito, mas ficar só em palavras leva à pobreza.', 'Provérbios 14:23', 'Provérbios', 'diligencia'),

-- ADVERTÊNCIAS CONTRA A PREGUIÇA (20)
('O preguiçoso diz: Um leão está no caminho; um leão está nas ruas.', 'Provérbios 26:13', 'Provérbios', 'preguica'),
('O desejo do preguiçoso o mata, porque as suas mãos recusam trabalhar.', 'Provérbios 21:25', 'Provérbios', 'preguica'),
('Preguiçoso, até quando ficarás deitado? Quando te levantarás do teu sono?', 'Provérbios 6:9', 'Provérbios', 'preguica'),
('Um pouco de sono, uma breve soneca, um pequeno descanso de braços cruzados, e a pobreza o surpreenderá.', 'Provérbios 6:10-11', 'Provérbios', 'preguica'),
('A preguiça faz cair em sono profundo, e a alma indolente padecerá fome.', 'Provérbios 19:15', 'Provérbios', 'preguica'),
('O caminho do preguiçoso é como uma sebe de espinhos.', 'Provérbios 15:19', 'Provérbios', 'preguica'),
('Como a porta se revolve nos seus gonzos, assim se revolve o preguiçoso na sua cama.', 'Provérbios 26:14', 'Provérbios', 'preguica'),
('O preguiçoso mete a mão no prato, e não tem disposição nem de levá-la à boca.', 'Provérbios 26:15', 'Provérbios', 'preguica'),
('O preguiçoso é mais sábio a seus próprios olhos do que sete homens que respondem com bom senso.', 'Provérbios 26:16', 'Provérbios', 'preguica'),
('Passei pelo campo do preguiçoso e pela vinha do homem falto de entendimento; e eis que toda estava cheia de cardos.', 'Provérbios 24:30-31', 'Provérbios', 'preguica'),
('O preguiçoso não assará a sua caça, mas o precioso tesouro do homem é ser diligente.', 'Provérbios 12:27', 'Provérbios', 'preguica'),
('A alma do preguiçoso deseja, e coisa nenhuma alcança.', 'Provérbios 13:4', 'Provérbios', 'preguica'),
('O ocioso na sua obra é irmão do desperdiçador.', 'Provérbios 18:9', 'Provérbios', 'preguica'),
('Pela muita preguiça se enfraquece o teto, e pela frouxidão das mãos a casa goteja.', 'Eclesiastes 10:18', 'Eclesiastes', 'preguica'),
('Se alguém não quer trabalhar, também não coma.', '2 Tessalonicenses 3:10', '2 Tessalonicenses', 'preguica'),
('Não ameis o sono, para que não empobreçais.', 'Provérbios 20:13', 'Provérbios', 'preguica'),
('O que ama o prazer empobrecerá.', 'Provérbios 21:17', 'Provérbios', 'preguica'),
('O preguiçoso esconde a mão no prato; não se dá ao trabalho de levá-la à boca.', 'Provérbios 19:24', 'Provérbios', 'preguica'),
('O que relaxa na sua obra é irmão do que é destruidor.', 'Provérbios 18:9', 'Provérbios', 'preguica'),
('O dorminhoco não lavrará por causa do inverno; mas na sega buscará e nada haverá.', 'Provérbios 20:4', 'Provérbios', 'preguica'),

-- PLANEJAMENTO E SABEDORIA (15)
('Os planos bem elaborados levam à fartura; mas o apressado sempre acaba na miséria.', 'Provérbios 21:5', 'Provérbios', 'planejamento'),
('Entregue ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.', 'Provérbios 16:3', 'Provérbios', 'planejamento'),
('Muitos são os planos no coração do homem, mas o que prevalece é o propósito do Senhor.', 'Provérbios 19:21', 'Provérbios', 'planejamento'),
('O sábio de coração recebe os mandamentos.', 'Provérbios 10:8', 'Provérbios', 'planejamento'),
('O princípio da sabedoria é: Adquire a sabedoria; sim, com tudo o que possuis adquire o entendimento.', 'Provérbios 4:7', 'Provérbios', 'planejamento'),
('Sem conselho, os planos se dispersam, mas havendo muitos conselheiros eles se firmam.', 'Provérbios 15:22', 'Provérbios', 'planejamento'),
('Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.', 'Provérbios 3:5', 'Provérbios', 'planejamento'),
('O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.', 'Provérbios 16:9', 'Provérbios', 'planejamento'),
('Com sabedoria se edifica a casa, e com inteligência ela se firma.', 'Provérbios 24:3', 'Provérbios', 'planejamento'),
('Porque qual é o homem que, querendo edificar uma torre, não se assenta primeiro a fazer as contas dos gastos?', 'Lucas 14:28', 'Lucas', 'planejamento'),
('A sabedoria é a coisa principal; adquire, pois, a sabedoria.', 'Provérbios 4:7', 'Provérbios', 'planejamento'),
('Conselhos na presença de muitos conselheiros.', 'Provérbios 11:14', 'Provérbios', 'planejamento'),
('Mas os planos do diligente tendem à fartura.', 'Provérbios 21:5', 'Provérbios', 'planejamento'),
('Pela sabedoria se edifica a casa, e pela inteligência ela se firma.', 'Provérbios 24:3', 'Provérbios', 'planejamento'),
('Procure saber o estado das suas ovelhas, cuide bem dos seus rebanhos.', 'Provérbios 27:23', 'Provérbios', 'planejamento'),

-- PERSEVERANÇA E RESILIÊNCIA (15)
('E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.', 'Gálatas 6:9', 'Gálatas', 'perseveranca'),
('Portanto, meus amados irmãos, sede firmes, inabaláveis e sempre abundantes na obra do Senhor.', '1 Coríntios 15:58', '1 Coríntios', 'perseveranca'),
('O justo cairá sete vezes, mas se levantará.', 'Provérbios 24:16', 'Provérbios', 'perseveranca'),
('Posso todas as coisas naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 'perseveranca'),
('Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.', 'Isaías 41:10', 'Isaías', 'perseveranca'),
('Pois o Senhor teu Deus estará contigo por onde quer que andares.', 'Josué 1:9', 'Josué', 'perseveranca'),
('A esperança que se adia faz o coração adoecer, mas o desejo cumprido é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 'perseveranca'),
('Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu.', 'Eclesiastes 3:1', 'Eclesiastes', 'perseveranca'),
('Não deixe que a sua boca o leve ao pecado, nem desanime diante das dificuldades.', 'Eclesiastes 5:6', 'Eclesiastes', 'perseveranca'),
('Porque sete vezes cairá o justo, e se levantará; mas os ímpios tropeçarão no mal.', 'Provérbios 24:16', 'Provérbios', 'perseveranca'),
('Os que semeiam em lágrimas colherão com alegria.', 'Salmos 126:5', 'Salmos', 'perseveranca'),
('Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz.', 'Jeremias 29:11', 'Jeremias', 'perseveranca'),
('Ainda que a figueira não floresça, eu me alegrarei no Senhor.', 'Habacuque 3:17-18', 'Habacuque', 'perseveranca'),
('Combati o bom combate, acabei a carreira, guardei a fé.', '2 Timóteo 4:7', '2 Timóteo', 'perseveranca'),
('Portanto, não lanceis fora a vossa confiança, que tem grande recompensa.', 'Hebreus 10:35', 'Hebreus', 'perseveranca'),

-- FÉ E CONFIANÇA EM DEUS (15)
('Confia no Senhor de todo o teu coração.', 'Provérbios 3:5', 'Provérbios', 'fe'),
('Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.', 'Salmos 37:5', 'Salmos', 'fe'),
('O Senhor é o meu pastor; nada me faltará.', 'Salmos 23:1', 'Salmos', 'fe'),
('Tudo posso naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 'fe'),
('Buscai primeiro o reino de Deus e a sua justiça, e todas estas coisas vos serão acrescentadas.', 'Mateus 6:33', 'Mateus', 'fe'),
('Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.', 'Provérbios 3:6', 'Provérbios', 'fe'),
('A bênção do Senhor enriquece, e não acrescenta dores.', 'Provérbios 10:22', 'Provérbios', 'fe'),
('Bem-aventurado o homem que teme ao Senhor e que muito se deleita nos seus mandamentos.', 'Salmos 112:1', 'Salmos', 'fe'),
('Confiai no Senhor perpetuamente; porque o Senhor Deus é uma rocha eterna.', 'Isaías 26:4', 'Isaías', 'fe'),
('O Senhor é bom, fortaleza no dia da angústia, e conhece os que nele confiam.', 'Naum 1:7', 'Naum', 'fe'),
('Aquietai-vos e sabei que eu sou Deus.', 'Salmos 46:10', 'Salmos', 'fe'),
('Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus.', 'Efésios 2:8', 'Efésios', 'fe'),
('Ora, a fé é a certeza das coisas que se esperam, a convicção de fatos que se não veem.', 'Hebreus 11:1', 'Hebreus', 'fe'),
('E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.', 'Romanos 8:28', 'Romanos', 'fe'),
('Lança o teu pão sobre as águas, porque, depois de muitos dias, o acharás.', 'Eclesiastes 11:1', 'Eclesiastes', 'fe'),

-- PROSPERIDADE E RECOMPENSA (10)
('Honra ao Senhor com os teus bens e com as primícias de toda a tua renda; assim, se encherão fartamente os teus celeiros.', 'Provérbios 3:9-10', 'Provérbios', 'prosperidade'),
('Trazei todos os dízimos à casa do tesouro, e provai-me nisto, diz o Senhor dos Exércitos.', 'Malaquias 3:10', 'Malaquias', 'prosperidade'),
('Bem-aventurado o homem que teme ao Senhor. A riqueza e a prosperidade estarão na sua casa.', 'Salmos 112:1-3', 'Salmos', 'prosperidade'),
('O bom deixa uma herança aos filhos de seus filhos, mas a riqueza do pecador é depositada para o justo.', 'Provérbios 13:22', 'Provérbios', 'prosperidade'),
('Quem dá ao pobre empresta ao Senhor, e este lhe pagará o seu benefício.', 'Provérbios 19:17', 'Provérbios', 'prosperidade'),
('Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos deitarão no vosso regaço.', 'Lucas 6:38', 'Lucas', 'prosperidade'),
('A alma generosa prosperará, e quem dá alívio aos outros, alívio receberá.', 'Provérbios 11:25', 'Provérbios', 'prosperidade'),
('Algumas pessoas dão generosamente, mas acabam com mais ainda; outras não dão o que devem e empobrecem.', 'Provérbios 11:24', 'Provérbios', 'prosperidade'),
('Riqueza e honra estão comigo, assim como prosperidade duradoura e justiça.', 'Provérbios 8:18', 'Provérbios', 'prosperidade'),
('O salário do justo conduz para a vida.', 'Provérbios 10:16', 'Provérbios', 'prosperidade'),

-- PALAVRAS E COMUNICAÇÃO (10)
('A resposta branda desvia o furor, mas a palavra dura suscita a ira.', 'Provérbios 15:1', 'Provérbios', 'comunicacao'),
('A morte e a vida estão no poder da língua; o que bem a utiliza come do seu fruto.', 'Provérbios 18:21', 'Provérbios', 'comunicacao'),
('O homem se alegra em dar uma resposta adequada, e como é boa uma palavra dita na hora certa!', 'Provérbios 15:23', 'Provérbios', 'comunicacao'),
('A palavra dita a seu tempo quão boa é!', 'Provérbios 15:23', 'Provérbios', 'comunicacao'),
('O favo de mel são as palavras suaves: doces para a alma e medicina para o corpo.', 'Provérbios 16:24', 'Provérbios', 'comunicacao'),
('A língua dos sábios adorna a sabedoria, mas a boca dos tolos derrama a estultícia.', 'Provérbios 15:2', 'Provérbios', 'comunicacao'),
('Quem guarda a boca e a língua, guarda a sua alma das angústias.', 'Provérbios 21:23', 'Provérbios', 'comunicacao'),
('Seja a vossa palavra sempre agradável, temperada com sal, para que saibais como responder a cada um.', 'Colossenses 4:6', 'Colossenses', 'comunicacao'),
('A língua branda quebranta os ossos.', 'Provérbios 25:15', 'Provérbios', 'comunicacao'),
('O coração do justo medita no que há de responder, mas a boca dos ímpios derrama coisas más.', 'Provérbios 15:28', 'Provérbios', 'comunicacao');